language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
      rust: stable
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu MSRV=true
      rust: 1.41.0
    - env: TARGET=powerpc-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: stable

script:
  - if [ "$MSRV" = true ] ; then
      cargo test --verbose --all --release --target $TARGET;
    else
      cargo install cross --force;
      cross test --verbose --all --release --target $TARGET;
    fi
cache: cargo
