[package]
name = "hkdf"
version = "0.1.1"
authors = ["vladikoff"]
license = "MIT"
homepage = "https://github.com/vladikoff/rust-hkdf/"
repository = "https://github.com/vladikoff/rust-hkdf/"
description = "HMAC-based Extract-and-Expand Key Derivation Function (HKDF)"
keywords = [ "HKDF", "Crypto" ]
readme = "README.md"

[lib]
name = "hkdf"
path = "src/hkdf.rs"

[dependencies]
rust-crypto = "0.2.36"
rustc-serialize = "0.3.24"
